### ISSUE TITLE
Add functions for the pre computation part

### ISSUE THREAD

**Issue by sofiachiarenza** [sofiachiarenza/Blast.jl#9]
Add the function(s) to compute the $\tilde{T}$, the integrals of the Chebyshev polynomials against the Bessel functions.

**Comment by sofiachiarenza** [comment]
I added the function as it was in my laptop, I think it needs to be improved (no need to pass power spectrum). Also, tests need to be added but I need to figure out the power spectrum first.

**Comment by sofiachiarenza** [comment]
Test the $C_\ell$'s before closing

**Comment by sofiachiarenza** [comment]
@marcobonici I added documentation and and assert in compute_$\tilde{T}$. Couldn't come up with a reasonable test for that function, putting k_min = k_max breaks FastChebInterp so it can't be used as a test.

**Comment by marcobonici** [comment]
Maybe I am getting it wrong, but why should we test with k_max=k_min?

**Comment by sofiachiarenza** [comment]
> Maybe I am getting it wrong, but why should we test with k_max=k_min?

I wanted to check that the integrals should be 0 in that case

**Comment by marcobonici** [comment]
I think in this case the integration measure is blowing up and the integral is ill-defined.

**Comment by sofiachiarenza** [comment]
That's why there's no test but I put an assert to check that kmin<kmax!

**Comment by sofiachiarenza** [comment]
> I think in this case the integration measure is blowing up and the integral is ill-defined.

Can't think of any other simple check for that part though.

**Comment by marcobonici** [comment]
Then it's fine. We can come up with something better later, covering this corner 😜

**Comment by marcobonici** [comment]
A possible solution is to perform the $\tilde{T}$ calculation once, do all possible tests to ensure the correctness of the result, then store it and use it to check that the calculations are accurate.

The workflow would be:
1. Compute the $\tilde{T}$
2. Ensure the correctness of the result
3. Store the results (likely on Zenodo or GitHub Gist)
4. When doing the unit tests, use the functions in `Blast.jl` to compute the $\tilde{T}$ and compare with the stored ones

While this does NOT ensure correctness per se (we are still assuming the tests performed at point 2 are good!) this will check that we are not breaking anything in the future.

**Comment by sofiachiarenza** [comment]
@marcobonici now the tests run in <5mins and they pass (except for l=2 in the shear-shear case, we can discuss later about that case)

**Comment by marcobonici** [comment]
Open the PR, @sofiachiarenza , and I will review it.
